services:
  - type: web
    name: doctorbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: 7644782997:AAGRD4wXYs6_YHKlvUlne14ow37byBaqb5s
      - key: ADMIN_IDS
        value: 542839510,5960037916
    autoDeploy: true
    region: frankfurt