services:
  - type: web
    name: doctorbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TOKEN
        value: 7653011930:AAHbOO8DcnoRRaG-wXmgQG8YqnwUe4zTCUw
      - key: ADMIN_IDS
        value: 542839510,5960037916
    autoDeploy: true
    region: frankfurt