services:
  - type: web
    name: botdoctor
    env: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: 7644782997:AAGRD4wXYs6_YHKlvUlne14ow37byBaqb5s
      - key: ADMIN_IDS
        value: 542839510,5960037916
      - key: WEBHOOK_URL
        value: https://botdoctor.onrender.com
    autoDeploy: false
    branch: main